name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        working-directory: ./chat-area [section]-app
        run: npm install
      - name: Build application
        working-directory: ./chat-area [section]-app
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CHATFLOW_817CF }}
          channelId: live
          projectId: chatflow-817cf
          entryPoint: chat-area [section]-app